### ISSUE TITLE
Effectful bind?

### ISSUE THREAD

**Issue by justinwoo** [bodil/purescript-observable#1]
Would probably have to be a new method, but would an effectual bind be okay to have in the library? I'm currently doing things like this:

``` purescript
let results = (requests <|> timer) >>= \request ->
    unsafePerformEff $ fromCallback $ runFn3 runTorscraper torscraperPath request
```

[source](https://github.com/justinwoo/simple-rpc-telegram-bot/blob/387377c19cf243b3854e8d9666909d49a6b7e77c/src/Main.purs#L118-L127)

**Comment by bodil** [comment]
That's what https://pursuit.purescript.org/packages/purescript-observable/2.2.0/docs/Control.Observable#v:unwrap is supposed to be for - would something like this work? (If that typechecks - I'm just making it up but that's the general idea.)

``` purescript
results <- unwrap ((requests <|> timer) >>= \request ->
    fromCallback $ runFn3 runTorscraper torscraperPath request)
```

**Comment by justinwoo** [comment]
Sorry, I don't understand. In my case, my `fromCallback` will give me back `Eff (observable :: OBSERVABLE | e) (Observable b)`, so I am looking to lift the Eff so that my function satisfies `(a -> Observable b)`.

My hacky solution would be something like this, but probably I'm missing something:

``` purescript
bindEff :: forall e a b. Observable a -> (a -> EffO e (Observable b)) -> Observable b
bindEff o f = o >>= f >>> unsafePerformEff

let results = (requests <|> timer) `bindEff` \request ->
    fromCallback $ runFn3 runTorscraper torscraperPath request
```

**Comment by bodil** [comment]
You'd have to call that `unsafeBindEff` because it absolutely is. :)

At a minimum, it needs to return `EffO e (Observable b)`, because you're causing side effects in the function being bound, so the bind is also impure. And at that point, as far as I can tell, it's just a specialised form of `bind`, which you might as well be using instead.

**Comment by justinwoo** [comment]
Yeah, I was thinking that this kind of effectual binding was common enough that it'd be nice to have it separate from the normal bind. Even as an alias to the ffi bind it'd be nice (I plan to use EffO e (Observable b) for this, this is just a hack to use it now)

**Comment by bodil** [comment]
I'm not sure I understand the use case - can you give an example of how you'd use it?

**Comment by justinwoo** [comment]
I'm using my hacky version [here](https://github.com/justinwoo/simple-rpc-telegram-bot/blob/master/src/Main.purs#L105-L124), where I have a chat bot that will run another program on an interval and on request for its output. The result of running the other program is then used to send a message, the gist of it being:

``` purescript
  let results = (requests <|> timer) `bindEff` \request ->
    liftAff $ runTorscraper torscraperPath request
  subscribe
    { next: (sendMessage bot)
    -- ...
    } results
```
