### ISSUE TITLE
fromCallback/lift(Aff/Cont)?

### ISSUE THREAD

**Issue by justinwoo** [bodil/purescript-observable#2]
It seems like these kinds of things come up often enough, where I've written a helper like this to get an Observable from a callback:

``` purescript
fromCallback :: forall e a b.
  (
    (a -> Eff (observable :: OBSERVABLE | e) Unit) ->
    Eff (observable :: OBSERVABLE | e) b
  )
  -> Eff (observable :: OBSERVABLE | e) (Observable a)
fromCallback source = observable \sink -> do
  source sink.next
  free []
```

and over in purescript-rx, Antti has added some convenience functions for lifting Affs and ContTs into Observables.

Would it make sense to have these in the library also?

**Comment by bodil** [comment]
I'm trying to keep the core library as light on dependencies as I can - I had a separate library in mind for these, in the spirit of `purescript-observable-time` etc, and I even meant to write it as part of the initial development, but I didn't get around to it.

If you've already got code for it, I'd say go for it, put it in a library and publish it. :)

**Comment by bodil** [comment]
(Or, if you'd rather not maintain it, I'd be happy to do it, just let me know.)

**Comment by justinwoo** [comment]
Cool, I'll add at least my callback lifter and start a lib for these.
